spring.application.name=pg
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.url=YOUR_DB_URL
spring.datasource.username=YOUR_USERNAME
spring.datasource.password=YOUR_PASSWORD
jwt.secret=YOUR_SECRET_KEY
jwt.access.expiry=YOUR_ACCESS_EXPIRY
jwt.refresh.expiry=YOUR_REFRESH_EXPIRY